[package]
name = "tarkov-quest-helper"
version = "0.1.0"
description = "Tarkov Quest Helper"
authors = ["you"]
edition = "2021"

[lib]
name = "tarkov_quest_helper_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify = { version = "7", features = ["serde"] }
regex = "1"
